# Generated by Django 5.0.2 on 2024-02-10 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
