# Generated by Django 5.0.2 on 2024-02-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
