# Generated by Django 5.0.2 on 2024-02-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_order_deliverydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
