# Generated by Django 5.0.2 on 2024-02-09 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_orderproduct_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
