# Generated by Django 5.0.2 on 2024-03-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_orderproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.TextField(default=''),
        ),
    ]
